/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 model/montana.gltf 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/montana.gltf')
 
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[0.471, 1.32, 0.22]} rotation={[-0.113, 0.173, 0.02]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[3.549, 1.32, 0.506]} rotation={[-2.424, 0.603, 2.682]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[3.049, 1.32, -1.699]} rotation={[-0.856, 1.101, 0.799]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[2.879, 1.314, 0.853]} rotation={[-0.591, -0.752, -0.43]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[5.61, 1.341, 0.58]} rotation={[-2.511, -0.649, -2.726]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[5.086, 1.37, -1.326]} rotation={[-2.918, -0.048, -3.131]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[6.356, 1.32, 1.442]} rotation={[-2.337, -0.792, -2.505]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[7.184, 1.348, 1.323]} rotation={[-1.27, -1.168, -1.246]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[7.022, 1.299, -0.977]} rotation={[-0.73, 1.403, 0.723]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[9.394, 1.345, 1.552]} rotation={[-0.53, 0.379, 0.214]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[8.747, 1.308, 0.759]} rotation={[-0.831, 0.987, 0.74]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[5.924, 1.328, 4.036]} rotation={[-2.806, -0.405, -3.005]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[9.495, 1.351, 5.638]} rotation={[-1.939, 0.361, 2.4]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[9.332, 1.358, 8.399]} rotation={[-0.88, 0.926, 0.769]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[7.831, 1.353, 8.548]} rotation={[-0.48, 0.736, 0.336]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[6.29, 1.359, 5.61]} rotation={[-2.52, -1.038, -2.589]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[5.611, 1.375, 10.268]} rotation={[-0.544, -1.367, -0.534]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[4.953, 1.38, 13.209]} rotation={[-1.505, -1.081, -1.496]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[8.888, 1.355, 10.129]} rotation={[2.896, 1.456, -2.897]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[8.468, 1.356, 12.634]} rotation={[-1.409, -0.74, -1.333]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[9.295, 1.444, 13.491]} rotation={[-0.999, -0.023, -0.035]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[10.015, 1.231, 11.589]} rotation={[-1.458, 0.627, 1.381]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[3.805, 1.227, 6.118]} rotation={[-0.325, 0.528, 0.168]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[-1.016, 1.207, 4.764]} rotation={[-0.251, 0.627, 0.149]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[3.858, 1.224, 2.364]} rotation={[-2.914, -0.783, -2.98]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[1.267, 1.179, 5.445]} rotation={[-0.785, 1.087, 0.724]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[-3.248, 1.098, 12.142]} rotation={[-0.444, -0.973, -0.375]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[1.582, 1.166, 14.934]} rotation={[-0.476, -0.174, -0.089]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[-3.347, 1.155, 1.584]} rotation={[-2.725, -1.38, -2.731]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[4.183, 1.229, -5.202]} rotation={[-0.614, -1.112, -0.564]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[9.042, 1.201, -4.292]} rotation={[-2.332, -0.82, -2.488]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[13.419, 1.153, -0.31]} rotation={[-2.576, 0.041, 3.115]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[13.446, 0.983, 15.189]} rotation={[-0.67, 0.132, 0.104]} />
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={58.716} position={[-2.114, 1.32, -5.22]} rotation={[-1.435, -0.879, -1.395]} />
      <mesh geometry={nodes.ROOM.geometry} material={materials['My_UV-texture_UVMAT.025']} />
      <mesh geometry={nodes.CORRIDOR.geometry} material={materials['My_UV-texture_UVMAT.021']} />
      <mesh geometry={nodes.ROOM_CHILDREN.geometry} material={materials['My_UV-texture_UVMAT.029']} position={[3.612, 0, -1.355]} />
      <mesh geometry={nodes.ROOM_BATH.geometry} material={materials['My_UV-texture_UVMAT.026']} position={[5.436, 0, -1.368]} />
      <mesh geometry={nodes.ROOM_ENGINEERING.geometry} material={materials['My_UV-texture_UVMAT']} position={[7.874, 0, -0.427]} />
      <mesh geometry={nodes.ROOM_LIVING.geometry} material={materials['My_UV-texture_UVMAT.031']} position={[6.299, 0, 3.197]} />
      <mesh geometry={nodes.ROOM_BED.geometry} material={materials['My_UV-texture_UVMAT.028']} position={[6.31, 0, 10.76]} />
      <mesh geometry={nodes.ROOM_STORAGE.geometry} material={materials['My_UV-texture_UVMAT.032']} position={[8.516, 0, 10.858]} />
      <mesh geometry={nodes.ROOM_BATH2.geometry} material={materials['My_UV-texture_UVMAT.027']} position={[8.487, 0, 12.698]} />
      <mesh geometry={nodes.POOL.geometry} material={materials['My_UV-texture_UVMAT.023']} />
      <mesh geometry={nodes.GARDEN.geometry} material={materials['My_UV-texture_UVMAT.038']} position={[-3.829, -0.061, 11.814]} />
      <mesh geometry={nodes.PARKING.geometry} material={materials['My_UV-texture_UVMAT.022']} position={[9.073, -0.058, -4.855]} />
      <mesh geometry={nodes.POOL_HOME.geometry} material={materials['My_UV-texture_UVMAT.024']} />
      <mesh geometry={nodes.BACKGROUND.geometry} material={materials['My_UV-texture_UVMAT.037']} position={[-11.66, -0.058, -5.636]} />
    </group>
  )
}

useGLTF.preload('/montana.gltf')
